"""
To be run on AWS Glue Runtime
"""

# TODO: Below code is tentative and never run on AWS. Make sure to run on AWS or use the one generated by AWS
from awsglue.context import GlueContext
from pyspark.context import SparkContext
from transformations import transform_xyz

sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session

# Read input
# TODO: Write code for reading input, use spark session defined above, refer spark-runtime version of it

# Run transformation
df_transformed = transform_xyz(df)

# Convert back to DynamicFrame and write to Glue Catalog or S3
dyf_out = DynamicFrame.fromDF(df_transformed, glueContext, "output_dyf")
glueContext.write_dynamic_frame.from_options(
    frame=dyf_out,
    connection_type="s3",
    connection_options={"path": "s3://mybucket/output/"},
    format="parquet"
)
